name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: release

    permissions:
      id-token: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: install dependencies and build package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1